// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: internal/appproto/proto/link.proto

package appproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BatchLink struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`     // идентификатор
	Link string `protobuf:"bytes,2,opt,name=link,proto3" json:"link,omitempty"` // ссылка
}

func (x *BatchLink) Reset() {
	*x = BatchLink{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_appproto_proto_link_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BatchLink) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchLink) ProtoMessage() {}

func (x *BatchLink) ProtoReflect() protoreflect.Message {
	mi := &file_internal_appproto_proto_link_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchLink.ProtoReflect.Descriptor instead.
func (*BatchLink) Descriptor() ([]byte, []int) {
	return file_internal_appproto_proto_link_proto_rawDescGZIP(), []int{0}
}

func (x *BatchLink) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *BatchLink) GetLink() string {
	if x != nil {
		return x.Link
	}
	return ""
}

type Links struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ShortUri string `protobuf:"bytes,1,opt,name=short_uri,json=shortUri,proto3" json:"short_uri,omitempty"` // короткая ссылка
	FullUri  string `protobuf:"bytes,2,opt,name=full_uri,json=fullUri,proto3" json:"full_uri,omitempty"`    // полная ссылка ссылка
}

func (x *Links) Reset() {
	*x = Links{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_appproto_proto_link_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Links) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Links) ProtoMessage() {}

func (x *Links) ProtoReflect() protoreflect.Message {
	mi := &file_internal_appproto_proto_link_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Links.ProtoReflect.Descriptor instead.
func (*Links) Descriptor() ([]byte, []int) {
	return file_internal_appproto_proto_link_proto_rawDescGZIP(), []int{1}
}

func (x *Links) GetShortUri() string {
	if x != nil {
		return x.ShortUri
	}
	return ""
}

func (x *Links) GetFullUri() string {
	if x != nil {
		return x.FullUri
	}
	return ""
}

type PutLinkRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Link string `protobuf:"bytes,1,opt,name=link,proto3" json:"link,omitempty"` // ссылка начальная
}

func (x *PutLinkRequest) Reset() {
	*x = PutLinkRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_appproto_proto_link_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PutLinkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutLinkRequest) ProtoMessage() {}

func (x *PutLinkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_appproto_proto_link_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutLinkRequest.ProtoReflect.Descriptor instead.
func (*PutLinkRequest) Descriptor() ([]byte, []int) {
	return file_internal_appproto_proto_link_proto_rawDescGZIP(), []int{2}
}

func (x *PutLinkRequest) GetLink() string {
	if x != nil {
		return x.Link
	}
	return ""
}

type PutLinkResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ShortLink string `protobuf:"bytes,1,opt,name=short_link,json=shortLink,proto3" json:"short_link,omitempty"` // ссылка сокращенная
	Cooke     string `protobuf:"bytes,2,opt,name=cooke,proto3" json:"cooke,omitempty"`                          // токен сессии пользователя
	Error     string `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`                          // ошибка
}

func (x *PutLinkResponse) Reset() {
	*x = PutLinkResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_appproto_proto_link_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PutLinkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutLinkResponse) ProtoMessage() {}

func (x *PutLinkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_appproto_proto_link_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutLinkResponse.ProtoReflect.Descriptor instead.
func (*PutLinkResponse) Descriptor() ([]byte, []int) {
	return file_internal_appproto_proto_link_proto_rawDescGZIP(), []int{3}
}

func (x *PutLinkResponse) GetShortLink() string {
	if x != nil {
		return x.ShortLink
	}
	return ""
}

func (x *PutLinkResponse) GetCooke() string {
	if x != nil {
		return x.Cooke
	}
	return ""
}

func (x *PutLinkResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type PutBatchLinkRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BatchLink []*BatchLink `protobuf:"bytes,1,rep,name=batchLink,proto3" json:"batchLink,omitempty"` // ссылка начальная
}

func (x *PutBatchLinkRequest) Reset() {
	*x = PutBatchLinkRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_appproto_proto_link_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PutBatchLinkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutBatchLinkRequest) ProtoMessage() {}

func (x *PutBatchLinkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_appproto_proto_link_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutBatchLinkRequest.ProtoReflect.Descriptor instead.
func (*PutBatchLinkRequest) Descriptor() ([]byte, []int) {
	return file_internal_appproto_proto_link_proto_rawDescGZIP(), []int{4}
}

func (x *PutBatchLinkRequest) GetBatchLink() []*BatchLink {
	if x != nil {
		return x.BatchLink
	}
	return nil
}

type PutBatchLinkResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BatchLink []*BatchLink `protobuf:"bytes,1,rep,name=batchLink,proto3" json:"batchLink,omitempty"` // ссылка сокращенная
	Cooke     string       `protobuf:"bytes,2,opt,name=cooke,proto3" json:"cooke,omitempty"`         // токен сессии пользователя
	Error     string       `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`         // ошибка
}

func (x *PutBatchLinkResponse) Reset() {
	*x = PutBatchLinkResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_appproto_proto_link_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PutBatchLinkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutBatchLinkResponse) ProtoMessage() {}

func (x *PutBatchLinkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_appproto_proto_link_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutBatchLinkResponse.ProtoReflect.Descriptor instead.
func (*PutBatchLinkResponse) Descriptor() ([]byte, []int) {
	return file_internal_appproto_proto_link_proto_rawDescGZIP(), []int{5}
}

func (x *PutBatchLinkResponse) GetBatchLink() []*BatchLink {
	if x != nil {
		return x.BatchLink
	}
	return nil
}

func (x *PutBatchLinkResponse) GetCooke() string {
	if x != nil {
		return x.Cooke
	}
	return ""
}

func (x *PutBatchLinkResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type PingDataBaseRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *PingDataBaseRequest) Reset() {
	*x = PingDataBaseRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_appproto_proto_link_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PingDataBaseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingDataBaseRequest) ProtoMessage() {}

func (x *PingDataBaseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_appproto_proto_link_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingDataBaseRequest.ProtoReflect.Descriptor instead.
func (*PingDataBaseRequest) Descriptor() ([]byte, []int) {
	return file_internal_appproto_proto_link_proto_rawDescGZIP(), []int{6}
}

type PingDataBaseResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cooke string `protobuf:"bytes,1,opt,name=cooke,proto3" json:"cooke,omitempty"` // токен сессии пользователя
	Error string `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"` // ошибка
}

func (x *PingDataBaseResponse) Reset() {
	*x = PingDataBaseResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_appproto_proto_link_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PingDataBaseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingDataBaseResponse) ProtoMessage() {}

func (x *PingDataBaseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_appproto_proto_link_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingDataBaseResponse.ProtoReflect.Descriptor instead.
func (*PingDataBaseResponse) Descriptor() ([]byte, []int) {
	return file_internal_appproto_proto_link_proto_rawDescGZIP(), []int{7}
}

func (x *PingDataBaseResponse) GetCooke() string {
	if x != nil {
		return x.Cooke
	}
	return ""
}

func (x *PingDataBaseResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type GivLinkRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Link string `protobuf:"bytes,1,opt,name=link,proto3" json:"link,omitempty"` // сокращенная ссылка
}

func (x *GivLinkRequest) Reset() {
	*x = GivLinkRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_appproto_proto_link_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GivLinkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GivLinkRequest) ProtoMessage() {}

func (x *GivLinkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_appproto_proto_link_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GivLinkRequest.ProtoReflect.Descriptor instead.
func (*GivLinkRequest) Descriptor() ([]byte, []int) {
	return file_internal_appproto_proto_link_proto_rawDescGZIP(), []int{8}
}

func (x *GivLinkRequest) GetLink() string {
	if x != nil {
		return x.Link
	}
	return ""
}

type GivLinkResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Link  string `protobuf:"bytes,1,opt,name=link,proto3" json:"link,omitempty"`   // начальная ссылка
	Cooke string `protobuf:"bytes,2,opt,name=cooke,proto3" json:"cooke,omitempty"` // токен сессии пользователя
	Error string `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"` // ошибка
}

func (x *GivLinkResponse) Reset() {
	*x = GivLinkResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_appproto_proto_link_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GivLinkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GivLinkResponse) ProtoMessage() {}

func (x *GivLinkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_appproto_proto_link_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GivLinkResponse.ProtoReflect.Descriptor instead.
func (*GivLinkResponse) Descriptor() ([]byte, []int) {
	return file_internal_appproto_proto_link_proto_rawDescGZIP(), []int{9}
}

func (x *GivLinkResponse) GetLink() string {
	if x != nil {
		return x.Link
	}
	return ""
}

func (x *GivLinkResponse) GetCooke() string {
	if x != nil {
		return x.Cooke
	}
	return ""
}

func (x *GivLinkResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type GivUserLinksRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GivUserLinksRequest) Reset() {
	*x = GivUserLinksRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_appproto_proto_link_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GivUserLinksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GivUserLinksRequest) ProtoMessage() {}

func (x *GivUserLinksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_appproto_proto_link_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GivUserLinksRequest.ProtoReflect.Descriptor instead.
func (*GivUserLinksRequest) Descriptor() ([]byte, []int) {
	return file_internal_appproto_proto_link_proto_rawDescGZIP(), []int{10}
}

type GivUserLinksResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Links []*Links `protobuf:"bytes,1,rep,name=links,proto3" json:"links,omitempty"` // сокращенная ссылка
	Cooke string   `protobuf:"bytes,2,opt,name=cooke,proto3" json:"cooke,omitempty"` // токен сессии пользователя
	Error string   `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"` // ошибка
}

func (x *GivUserLinksResponse) Reset() {
	*x = GivUserLinksResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_appproto_proto_link_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GivUserLinksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GivUserLinksResponse) ProtoMessage() {}

func (x *GivUserLinksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_appproto_proto_link_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GivUserLinksResponse.ProtoReflect.Descriptor instead.
func (*GivUserLinksResponse) Descriptor() ([]byte, []int) {
	return file_internal_appproto_proto_link_proto_rawDescGZIP(), []int{11}
}

func (x *GivUserLinksResponse) GetLinks() []*Links {
	if x != nil {
		return x.Links
	}
	return nil
}

func (x *GivUserLinksResponse) GetCooke() string {
	if x != nil {
		return x.Cooke
	}
	return ""
}

func (x *GivUserLinksResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type DelUserLinksRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Links []string `protobuf:"bytes,1,rep,name=links,proto3" json:"links,omitempty"` // сокращенная ссылка
}

func (x *DelUserLinksRequest) Reset() {
	*x = DelUserLinksRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_appproto_proto_link_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DelUserLinksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DelUserLinksRequest) ProtoMessage() {}

func (x *DelUserLinksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_appproto_proto_link_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DelUserLinksRequest.ProtoReflect.Descriptor instead.
func (*DelUserLinksRequest) Descriptor() ([]byte, []int) {
	return file_internal_appproto_proto_link_proto_rawDescGZIP(), []int{12}
}

func (x *DelUserLinksRequest) GetLinks() []string {
	if x != nil {
		return x.Links
	}
	return nil
}

type DelUserLinksResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cooke string `protobuf:"bytes,1,opt,name=cooke,proto3" json:"cooke,omitempty"` // токен сессии пользователя
	Error string `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"` // ошибка
}

func (x *DelUserLinksResponse) Reset() {
	*x = DelUserLinksResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_appproto_proto_link_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DelUserLinksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DelUserLinksResponse) ProtoMessage() {}

func (x *DelUserLinksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_appproto_proto_link_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DelUserLinksResponse.ProtoReflect.Descriptor instead.
func (*DelUserLinksResponse) Descriptor() ([]byte, []int) {
	return file_internal_appproto_proto_link_proto_rawDescGZIP(), []int{13}
}

func (x *DelUserLinksResponse) GetCooke() string {
	if x != nil {
		return x.Cooke
	}
	return ""
}

func (x *DelUserLinksResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type StatRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *StatRequest) Reset() {
	*x = StatRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_appproto_proto_link_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatRequest) ProtoMessage() {}

func (x *StatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_appproto_proto_link_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatRequest.ProtoReflect.Descriptor instead.
func (*StatRequest) Descriptor() ([]byte, []int) {
	return file_internal_appproto_proto_link_proto_rawDescGZIP(), []int{14}
}

type StatResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CountUser  int32  `protobuf:"varint,1,opt,name=countUser,proto3" json:"countUser,omitempty"`   // кол-во пользователей
	CountLinks int32  `protobuf:"varint,2,opt,name=countLinks,proto3" json:"countLinks,omitempty"` // кол-во ссылок
	Error      string `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`            // ошибка
}

func (x *StatResponse) Reset() {
	*x = StatResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_appproto_proto_link_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatResponse) ProtoMessage() {}

func (x *StatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_appproto_proto_link_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatResponse.ProtoReflect.Descriptor instead.
func (*StatResponse) Descriptor() ([]byte, []int) {
	return file_internal_appproto_proto_link_proto_rawDescGZIP(), []int{15}
}

func (x *StatResponse) GetCountUser() int32 {
	if x != nil {
		return x.CountUser
	}
	return 0
}

func (x *StatResponse) GetCountLinks() int32 {
	if x != nil {
		return x.CountLinks
	}
	return 0
}

func (x *StatResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_internal_appproto_proto_link_proto protoreflect.FileDescriptor

var file_internal_appproto_proto_link_proto_rawDesc = []byte{
	0x0a, 0x22, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x61, 0x70, 0x70, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6c, 0x69, 0x6e, 0x6b, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x61, 0x70, 0x70, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x2f,
	0x0a, 0x09, 0x42, 0x61, 0x74, 0x63, 0x68, 0x4c, 0x69, 0x6e, 0x6b, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6c,
	0x69, 0x6e, 0x6b, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6c, 0x69, 0x6e, 0x6b, 0x22,
	0x3f, 0x0a, 0x05, 0x4c, 0x69, 0x6e, 0x6b, 0x73, 0x12, 0x1b, 0x0a, 0x09, 0x73, 0x68, 0x6f, 0x72,
	0x74, 0x5f, 0x75, 0x72, 0x69, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x73, 0x68, 0x6f,
	0x72, 0x74, 0x55, 0x72, 0x69, 0x12, 0x19, 0x0a, 0x08, 0x66, 0x75, 0x6c, 0x6c, 0x5f, 0x75, 0x72,
	0x69, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x66, 0x75, 0x6c, 0x6c, 0x55, 0x72, 0x69,
	0x22, 0x24, 0x0a, 0x0e, 0x50, 0x75, 0x74, 0x4c, 0x69, 0x6e, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6c, 0x69, 0x6e, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6c, 0x69, 0x6e, 0x6b, 0x22, 0x5c, 0x0a, 0x0f, 0x50, 0x75, 0x74, 0x4c, 0x69, 0x6e,
	0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x68, 0x6f,
	0x72, 0x74, 0x5f, 0x6c, 0x69, 0x6e, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73,
	0x68, 0x6f, 0x72, 0x74, 0x4c, 0x69, 0x6e, 0x6b, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x6f, 0x6b,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x63, 0x6f, 0x6f, 0x6b, 0x65, 0x12, 0x14,
	0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65,
	0x72, 0x72, 0x6f, 0x72, 0x22, 0x48, 0x0a, 0x13, 0x50, 0x75, 0x74, 0x42, 0x61, 0x74, 0x63, 0x68,
	0x4c, 0x69, 0x6e, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x31, 0x0a, 0x09, 0x62,
	0x61, 0x74, 0x63, 0x68, 0x4c, 0x69, 0x6e, 0x6b, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x13,
	0x2e, 0x61, 0x70, 0x70, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x42, 0x61, 0x74, 0x63, 0x68, 0x4c,
	0x69, 0x6e, 0x6b, 0x52, 0x09, 0x62, 0x61, 0x74, 0x63, 0x68, 0x4c, 0x69, 0x6e, 0x6b, 0x22, 0x75,
	0x0a, 0x14, 0x50, 0x75, 0x74, 0x42, 0x61, 0x74, 0x63, 0x68, 0x4c, 0x69, 0x6e, 0x6b, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x31, 0x0a, 0x09, 0x62, 0x61, 0x74, 0x63, 0x68, 0x4c,
	0x69, 0x6e, 0x6b, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x61, 0x70, 0x70, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x42, 0x61, 0x74, 0x63, 0x68, 0x4c, 0x69, 0x6e, 0x6b, 0x52, 0x09,
	0x62, 0x61, 0x74, 0x63, 0x68, 0x4c, 0x69, 0x6e, 0x6b, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x6f,
	0x6b, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x63, 0x6f, 0x6f, 0x6b, 0x65, 0x12,
	0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x65, 0x72, 0x72, 0x6f, 0x72, 0x22, 0x15, 0x0a, 0x13, 0x50, 0x69, 0x6e, 0x67, 0x44, 0x61, 0x74,
	0x61, 0x42, 0x61, 0x73, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x42, 0x0a, 0x14,
	0x50, 0x69, 0x6e, 0x67, 0x44, 0x61, 0x74, 0x61, 0x42, 0x61, 0x73, 0x65, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x6f, 0x6b, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x63, 0x6f, 0x6f, 0x6b, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72,
	0x72, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72,
	0x22, 0x24, 0x0a, 0x0e, 0x47, 0x69, 0x76, 0x4c, 0x69, 0x6e, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6c, 0x69, 0x6e, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6c, 0x69, 0x6e, 0x6b, 0x22, 0x51, 0x0a, 0x0f, 0x47, 0x69, 0x76, 0x4c, 0x69, 0x6e,
	0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6c, 0x69, 0x6e,
	0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6c, 0x69, 0x6e, 0x6b, 0x12, 0x14, 0x0a,
	0x05, 0x63, 0x6f, 0x6f, 0x6b, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x63, 0x6f,
	0x6f, 0x6b, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x22, 0x15, 0x0a, 0x13, 0x47, 0x69, 0x76,
	0x55, 0x73, 0x65, 0x72, 0x4c, 0x69, 0x6e, 0x6b, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x22, 0x69, 0x0a, 0x14, 0x47, 0x69, 0x76, 0x55, 0x73, 0x65, 0x72, 0x4c, 0x69, 0x6e, 0x6b, 0x73,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x25, 0x0a, 0x05, 0x6c, 0x69, 0x6e, 0x6b,
	0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x61, 0x70, 0x70, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x4c, 0x69, 0x6e, 0x6b, 0x73, 0x52, 0x05, 0x6c, 0x69, 0x6e, 0x6b, 0x73, 0x12,
	0x14, 0x0a, 0x05, 0x63, 0x6f, 0x6f, 0x6b, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x63, 0x6f, 0x6f, 0x6b, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x22, 0x2b, 0x0a, 0x13, 0x44,
	0x65, 0x6c, 0x55, 0x73, 0x65, 0x72, 0x4c, 0x69, 0x6e, 0x6b, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x69, 0x6e, 0x6b, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x09, 0x52, 0x05, 0x6c, 0x69, 0x6e, 0x6b, 0x73, 0x22, 0x42, 0x0a, 0x14, 0x44, 0x65, 0x6c, 0x55,
	0x73, 0x65, 0x72, 0x4c, 0x69, 0x6e, 0x6b, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x6f, 0x6b, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x63, 0x6f, 0x6f, 0x6b, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x22, 0x0d, 0x0a, 0x0b,
	0x53, 0x74, 0x61, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x62, 0x0a, 0x0c, 0x53,
	0x74, 0x61, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x55, 0x73, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x55, 0x73, 0x65, 0x72, 0x12, 0x1e, 0x0a, 0x0a, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x4c, 0x69, 0x6e, 0x6b, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x4c, 0x69, 0x6e, 0x6b, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72,
	0x6f, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x32,
	0x81, 0x04, 0x0a, 0x0c, 0x4c, 0x69, 0x6e, 0x6b, 0x73, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x12, 0x3e, 0x0a, 0x07, 0x50, 0x75, 0x74, 0x4c, 0x69, 0x6e, 0x6b, 0x12, 0x18, 0x2e, 0x61, 0x70,
	0x70, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x50, 0x75, 0x74, 0x4c, 0x69, 0x6e, 0x6b, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x61, 0x70, 0x70, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x50, 0x75, 0x74, 0x4c, 0x69, 0x6e, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x4d, 0x0a, 0x0c, 0x50, 0x75, 0x74, 0x42, 0x61, 0x74, 0x63, 0x68, 0x4c, 0x69, 0x6e, 0x6b,
	0x12, 0x1d, 0x2e, 0x61, 0x70, 0x70, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x50, 0x75, 0x74, 0x42,
	0x61, 0x74, 0x63, 0x68, 0x4c, 0x69, 0x6e, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x1e, 0x2e, 0x61, 0x70, 0x70, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x50, 0x75, 0x74, 0x42, 0x61,
	0x74, 0x63, 0x68, 0x4c, 0x69, 0x6e, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x4d, 0x0a, 0x0c, 0x50, 0x69, 0x6e, 0x67, 0x44, 0x61, 0x74, 0x61, 0x42, 0x61, 0x73, 0x65, 0x12,
	0x1d, 0x2e, 0x61, 0x70, 0x70, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x50, 0x69, 0x6e, 0x67, 0x44,
	0x61, 0x74, 0x61, 0x42, 0x61, 0x73, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e,
	0x2e, 0x61, 0x70, 0x70, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x50, 0x69, 0x6e, 0x67, 0x44, 0x61,
	0x74, 0x61, 0x42, 0x61, 0x73, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3e,
	0x0a, 0x07, 0x47, 0x69, 0x76, 0x4c, 0x69, 0x6e, 0x6b, 0x12, 0x18, 0x2e, 0x61, 0x70, 0x70, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x47, 0x69, 0x76, 0x4c, 0x69, 0x6e, 0x6b, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x61, 0x70, 0x70, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x47,
	0x69, 0x76, 0x4c, 0x69, 0x6e, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4d,
	0x0a, 0x0c, 0x47, 0x69, 0x76, 0x55, 0x73, 0x65, 0x72, 0x4c, 0x69, 0x6e, 0x6b, 0x73, 0x12, 0x1d,
	0x2e, 0x61, 0x70, 0x70, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x47, 0x69, 0x76, 0x55, 0x73, 0x65,
	0x72, 0x4c, 0x69, 0x6e, 0x6b, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e,
	0x61, 0x70, 0x70, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x47, 0x69, 0x76, 0x55, 0x73, 0x65, 0x72,
	0x4c, 0x69, 0x6e, 0x6b, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4d, 0x0a,
	0x0c, 0x44, 0x65, 0x6c, 0x55, 0x73, 0x65, 0x72, 0x4c, 0x69, 0x6e, 0x6b, 0x73, 0x12, 0x1d, 0x2e,
	0x61, 0x70, 0x70, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x44, 0x65, 0x6c, 0x55, 0x73, 0x65, 0x72,
	0x4c, 0x69, 0x6e, 0x6b, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x61,
	0x70, 0x70, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x44, 0x65, 0x6c, 0x55, 0x73, 0x65, 0x72, 0x4c,
	0x69, 0x6e, 0x6b, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x35, 0x0a, 0x04,
	0x53, 0x74, 0x61, 0x74, 0x12, 0x15, 0x2e, 0x61, 0x70, 0x70, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x53, 0x74, 0x61, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x61, 0x70,
	0x70, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x42, 0x2e, 0x5a, 0x2c, 0x48, 0x61, 0x70, 0x70, 0x79, 0x4b, 0x6f, 0x64, 0x2f,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x4c, 0x69, 0x6e, 0x6b,
	0x73, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x61, 0x70, 0x70, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_internal_appproto_proto_link_proto_rawDescOnce sync.Once
	file_internal_appproto_proto_link_proto_rawDescData = file_internal_appproto_proto_link_proto_rawDesc
)

func file_internal_appproto_proto_link_proto_rawDescGZIP() []byte {
	file_internal_appproto_proto_link_proto_rawDescOnce.Do(func() {
		file_internal_appproto_proto_link_proto_rawDescData = protoimpl.X.CompressGZIP(file_internal_appproto_proto_link_proto_rawDescData)
	})
	return file_internal_appproto_proto_link_proto_rawDescData
}

var file_internal_appproto_proto_link_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_internal_appproto_proto_link_proto_goTypes = []interface{}{
	(*BatchLink)(nil),            // 0: appproto.BatchLink
	(*Links)(nil),                // 1: appproto.Links
	(*PutLinkRequest)(nil),       // 2: appproto.PutLinkRequest
	(*PutLinkResponse)(nil),      // 3: appproto.PutLinkResponse
	(*PutBatchLinkRequest)(nil),  // 4: appproto.PutBatchLinkRequest
	(*PutBatchLinkResponse)(nil), // 5: appproto.PutBatchLinkResponse
	(*PingDataBaseRequest)(nil),  // 6: appproto.PingDataBaseRequest
	(*PingDataBaseResponse)(nil), // 7: appproto.PingDataBaseResponse
	(*GivLinkRequest)(nil),       // 8: appproto.GivLinkRequest
	(*GivLinkResponse)(nil),      // 9: appproto.GivLinkResponse
	(*GivUserLinksRequest)(nil),  // 10: appproto.GivUserLinksRequest
	(*GivUserLinksResponse)(nil), // 11: appproto.GivUserLinksResponse
	(*DelUserLinksRequest)(nil),  // 12: appproto.DelUserLinksRequest
	(*DelUserLinksResponse)(nil), // 13: appproto.DelUserLinksResponse
	(*StatRequest)(nil),          // 14: appproto.StatRequest
	(*StatResponse)(nil),         // 15: appproto.StatResponse
}
var file_internal_appproto_proto_link_proto_depIdxs = []int32{
	0,  // 0: appproto.PutBatchLinkRequest.batchLink:type_name -> appproto.BatchLink
	0,  // 1: appproto.PutBatchLinkResponse.batchLink:type_name -> appproto.BatchLink
	1,  // 2: appproto.GivUserLinksResponse.links:type_name -> appproto.Links
	2,  // 3: appproto.LinksService.PutLink:input_type -> appproto.PutLinkRequest
	4,  // 4: appproto.LinksService.PutBatchLink:input_type -> appproto.PutBatchLinkRequest
	6,  // 5: appproto.LinksService.PingDataBase:input_type -> appproto.PingDataBaseRequest
	8,  // 6: appproto.LinksService.GivLink:input_type -> appproto.GivLinkRequest
	10, // 7: appproto.LinksService.GivUserLinks:input_type -> appproto.GivUserLinksRequest
	12, // 8: appproto.LinksService.DelUserLinks:input_type -> appproto.DelUserLinksRequest
	14, // 9: appproto.LinksService.Stat:input_type -> appproto.StatRequest
	3,  // 10: appproto.LinksService.PutLink:output_type -> appproto.PutLinkResponse
	5,  // 11: appproto.LinksService.PutBatchLink:output_type -> appproto.PutBatchLinkResponse
	7,  // 12: appproto.LinksService.PingDataBase:output_type -> appproto.PingDataBaseResponse
	9,  // 13: appproto.LinksService.GivLink:output_type -> appproto.GivLinkResponse
	11, // 14: appproto.LinksService.GivUserLinks:output_type -> appproto.GivUserLinksResponse
	13, // 15: appproto.LinksService.DelUserLinks:output_type -> appproto.DelUserLinksResponse
	15, // 16: appproto.LinksService.Stat:output_type -> appproto.StatResponse
	10, // [10:17] is the sub-list for method output_type
	3,  // [3:10] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_internal_appproto_proto_link_proto_init() }
func file_internal_appproto_proto_link_proto_init() {
	if File_internal_appproto_proto_link_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_internal_appproto_proto_link_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BatchLink); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_appproto_proto_link_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Links); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_appproto_proto_link_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PutLinkRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_appproto_proto_link_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PutLinkResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_appproto_proto_link_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PutBatchLinkRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_appproto_proto_link_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PutBatchLinkResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_appproto_proto_link_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PingDataBaseRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_appproto_proto_link_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PingDataBaseResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_appproto_proto_link_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GivLinkRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_appproto_proto_link_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GivLinkResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_appproto_proto_link_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GivUserLinksRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_appproto_proto_link_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GivUserLinksResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_appproto_proto_link_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DelUserLinksRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_appproto_proto_link_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DelUserLinksResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_appproto_proto_link_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StatRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_appproto_proto_link_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StatResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_internal_appproto_proto_link_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_appproto_proto_link_proto_goTypes,
		DependencyIndexes: file_internal_appproto_proto_link_proto_depIdxs,
		MessageInfos:      file_internal_appproto_proto_link_proto_msgTypes,
	}.Build()
	File_internal_appproto_proto_link_proto = out.File
	file_internal_appproto_proto_link_proto_rawDesc = nil
	file_internal_appproto_proto_link_proto_goTypes = nil
	file_internal_appproto_proto_link_proto_depIdxs = nil
}
